In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('unclean_smartwatch_health_data.csv')

In [4]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [6]:
df['User ID'].isnull().sum()

np.int64(201)

In [7]:
df.drop(columns=['User ID'])

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6
...,...,...,...,...,...,...
9995,78.819386,98.931927,2948.491953,7.402748595032027,Active,7
9996,48.632659,95.773035,4725.623070,6.3821659358529015,Sedentary,2
9997,73.834442,97.945874,2571.492060,6.91654920303435,Sedentary,4
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8
9999,70.063864,98.475606,544.696104,5.691001039740254,Actve,5

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 811.5 KB

In [9]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [10]:
df[df['Heart Rate (BPM)'].isnull()==True]

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,3919.0,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,3945.0,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,2981.0,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,4099.0,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...,...
9875,NaN,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,1476.0,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,1434.0,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,4907.0,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [11]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [ ]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [13]:
df['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [16]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [17]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)